name: mumhelpmum
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ---- App dependencies（与 flutter: 同级）----
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_riverpod: ^3.0.3
  speech_to_text: ^7.3.0
  cloud_firestore: ^5.6.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
